version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
      - ./app/node_modules
  myblog:
    build: ./frontend
    container_name: myblog_c
    ports:
      - '3000:3000'
    stdin_open: true